# Generated by Django 5.0.2 on 2024-02-14 14:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.TextField()),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=255)),
                ("price", models.FloatField()),
            ],
            options={
                "db_table": "products",
            },
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("telegram_id", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(max_length=255)),
                ("balance", models.FloatField()),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="UserCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "acquired_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogapp.products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogapp.users",
                    ),
                ),
            ],
            options={
                "db_table": "UserCards",
            },
        ),
    ]
